apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    apps: myapp
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"