apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    apps: myapp
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx
      readinessProbe:
        exec:
          command:
            - cat
            - /app/is_ready