apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    apps: myapp
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8