apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  securityContext:
    runAsUser: custom
  
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "120"]
      securityContext:
        runAsUser: custom
        capabilities:
          add: ["MAC_ADMIN"]