apiVersion: batch/v1
kind: Pod
metadata: 
  name: job-pod
spec:
  template:
    spec: 
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", "+", "2"]
      restartPolicy: Never