apiVersion: batch/v1
kind: Job
metadata: 
  name: job-pod
spec:
  completions: 3
  pararelism: 3
  template:
    spec: 
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", "+", "2"]
      restartPolicy: Never